### ISSUE TITLE
ComboBox and Select label styles differ from TextField

### ISSUE THREAD

**Issue by haase1020** [spear-ai/ui#221]
I noticed when using the ComboBox and Select components in the same form as a TextField component that the labels differ in styling. Is this intentional? If not, they should be normalized so they have the same styling. 

ComboBox label classes: `mb-2 block select-none text-base/6 text-neutral-12 group-disabled:text-neutral-11 sm:text-sm/6`
TextField label classes: `block text-sm font-medium leading-6 text-primary-12`

**Comment by psirenny** [comment]
I _think_ in the latest version they match now.

**Comment by psirenny** [comment]
I have to create a package for these components 😅.
